# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iHealthyLifestyle' do
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'


  use_frameworks!

  # Pods for iHealthyLifestyle

  target 'iHealthyLifestyleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
